import Head from "next/head";
import React from "react";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>{user.user?.firstName}</div>

        {!!user.isSignedIn && <SignOutButton>Sign out</SignOutButton>}
        {!user.isSignedIn && <SignInButton mode="modal">Sign in</SignInButton>}
      </main>
    </>
  );
}
